// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL_rL-bf7rbtKyYWqeZ0C1u6L2Ds0VSAE',
    appId: '1:1018881803803:web:b5660faa4a68ea8b331abe',
    messagingSenderId: '1018881803803',
    projectId: 'wisymobile',
    authDomain: 'wisymobile.firebaseapp.com',
    storageBucket: 'wisymobile.appspot.com',
    measurementId: 'G-PHP26P1P8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFFg5OJNLrfHVNt58kLb5wxW-_aXAk0IE',
    appId: '1:1018881803803:android:716e106e6226ebc6331abe',
    messagingSenderId: '1018881803803',
    projectId: 'wisymobile',
    storageBucket: 'wisymobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC42cC7nIy0XcxnxcSAKteAZNTYHKUSW1E',
    appId: '1:1018881803803:ios:83878d9db1f22164331abe',
    messagingSenderId: '1018881803803',
    projectId: 'wisymobile',
    storageBucket: 'wisymobile.appspot.com',
    iosBundleId: 'com.example.wisyMobileChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC42cC7nIy0XcxnxcSAKteAZNTYHKUSW1E',
    appId: '1:1018881803803:ios:83878d9db1f22164331abe',
    messagingSenderId: '1018881803803',
    projectId: 'wisymobile',
    storageBucket: 'wisymobile.appspot.com',
    iosBundleId: 'com.example.wisyMobileChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL_rL-bf7rbtKyYWqeZ0C1u6L2Ds0VSAE',
    appId: '1:1018881803803:web:f65555145293d443331abe',
    messagingSenderId: '1018881803803',
    projectId: 'wisymobile',
    authDomain: 'wisymobile.firebaseapp.com',
    storageBucket: 'wisymobile.appspot.com',
    measurementId: 'G-Q43X3TBR17',
  );

}